# Pre-Commit Hooks Docs: https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # https://pre-commit.com/hooks.html
    rev: v4.5.0
    hooks:
      - id: check-json
        exclude: 'devcontainer\.json' # regular expression
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
